# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Vercel Preview Deploy

on:
  pull_request_target:
    branches:
      - main

jobs:
  preview-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project (optional)
        run: echo "No build step needed for static site"

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel (Preview)
        id: vercel
        run: |
          DEPLOY_URL=$(vercel --token $VERCEL_TOKEN --scope $VERCEL_ORG_ID --confirm)
          echo "preview_url=$DEPLOY_URL" >> $GITHUB_OUTPUT
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

      - name: Comment PR with preview link
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🔍 **Preview Deploy Successful (Vercel)**\n\n🔗 Preview URL: ${{ steps.vercel.outputs.preview_url }}\n\n✅ Please review this deployment before merging.`
            })
